### ISSUE TITLE
[BUG] cars stalling and makes complete stop to rev for 5+ secs when going full speed

### ISSUE THREAD

**Issue by klipped** [qbcore-framework/qb-mechanicjob#67]
i dont know why i havent seen anyone post on this since i been having this issue for at least 2 months now. when i mess with the client/main.lua i just use "--" to disable the read of code to see whats causing it. i never can find exactly what line it is that cause these problems but when i -- the whole file i experience no problems at all... i also use jim mechanic but before i even had jim mechanic this problem was still one i couldnt find out. we can be going 200mph and the car will completely shut down and break soo hard and stand still and just revs while at a complete stop for some seconds, then itll let us drive again, then do the same thing shortly after......what is this???

**Comment by Sharkiiie** [comment]
Howdy!

This is handled in the `ApplyEffects()` function.
Basically if the vehicle is too damaged, it will start to fail and needs to be fixed by a mechanic.

I am not sure how Jim interacts with mechanicjob, but if you wish to disable this feature, you can comment out this function and any places where the function is called.
